### ISSUE TITLE
can not build with latest android sdl library 4.0

### ISSUE THREAD

**Issue by chinlin0924** [smartdevicelink/sdl_tester_android#24]
[javac] /projects/SDL/sdl_tester_android/LivioSdlUtilities/src/com/livio/sdl/SdlService.java:108: com.livio.sdl.SdlService is not abstract and does not override abstract method onServiceDataACK() in com.smartdevicelink.proxy.interfaces.IProxyListenerBase
    [javac] public class SdlService extends Service implements IProxyListenerALM{
    [javac]        ^
    [javac] 1 error
    [javac] 100 warnings

**Comment by joeygrover** [comment]
Closing as duplicate for #23
